"""Core domain and persistence package for SymptoThermalNFP."""

from .interpretation import (
    CycleInterpretation,
    CyclePhase,
    DailyInterpretation,
    FertilityStatus,
    InterpretationReport,
    InterpretationWarning,
    RuleTrace,
    TemperatureShift,
    WarningSeverity,
    evaluate_observations,
)
from .models import (
    AppSettings,
    CervicalPositionObservation,
    CycleSnapshot,
    DailyObservation,
    FluidObservation,
    build_cycle_history,
)
from .excel_store import ExcelStore, ExcelStoreError, ImportResult, build_workbook
from .storage import LocalStore
from .taxonomy import (
    BleedingLevel,
    CervixFirmness,
    CervixHeight,
    CervixOpening,
    FluidQuantity,
    FluidSensation,
    MucusColor,
    MucusTexture,
    RuleContext,
    TemperatureUnit,
)

__all__ = [
    "AppSettings",
    "BleedingLevel",
    "CervicalPositionObservation",
    "CycleInterpretation",
    "CyclePhase",
    "CervixFirmness",
    "CervixHeight",
    "CervixOpening",
    "CycleSnapshot",
    "DailyInterpretation",
    "DailyObservation",
    "ExcelStore",
    "ExcelStoreError",
    "ImportResult",
    "build_workbook",
    "FertilityStatus",
    "FluidObservation",
    "FluidQuantity",
    "FluidSensation",
    "InterpretationReport",
    "InterpretationWarning",
    "LocalStore",
    "MucusColor",
    "MucusTexture",
    "RuleContext",
    "RuleTrace",
    "TemperatureUnit",
    "TemperatureShift",
    "WarningSeverity",
    "build_cycle_history",
    "evaluate_observations",
]
